# Generated by Django 2.2.13 on 2020-06-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('cuisine', models.CharField(max_length=255)),
                ('expence', models.CharField(max_length=255)),
                ('offers', models.CharField(max_length=255)),
                ('waitTime', models.IntegerField()),
            ],
            options={
                'get_latest_by': 'waitTime',
            },
        ),
    ]
