# Generated by Django 2.2.13 on 2020-06-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('restaurant', models.CharField(max_length=255)),
                ('numberOfPeople', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
    ]
