# Generated by Django 2.2.13 on 2020-06-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('itemPrice', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
